import type { Section, StoreProfile } from "@/types";


export const DEFAULT_SECTIONS: Section[] = [
    { id: 'sec_fruit', name: 'Fruta y Verdura', icon: '🥦', defaultOrder: 0 },
    { id: 'sec_bakery', name: 'Panadería', icon: '🥖', defaultOrder: 1 },
    { id: 'sec_deli', name: 'Charcutería y Quesos', icon: '🧀', defaultOrder: 2 },
    { id: 'sec_meat', name: 'Carnicería', icon: '🥩', defaultOrder: 3 },
    { id: 'sec_fish', name: 'Pescadería', icon: '🐟', defaultOrder: 4 },
    { id: 'sec_fridge', name: 'Refrigerados', icon: '🍶', defaultOrder: 5 }, // yogures, pizzas, etc
    { id: 'sec_pantry', name: 'Despensa', icon: '🥫', defaultOrder: 6 }, // pasta, arroz, conservas
    { id: 'sec_frozen', name: 'Congelados', icon: '❄️', defaultOrder: 7 },
    { id: 'sec_drinks', name: 'Bebidas', icon: '🥤', defaultOrder: 8 },
    { id: 'sec_cleaning', name: 'Limpieza y Hogar', icon: '🧹', defaultOrder: 9 },
    { id: 'sec_personal', name: 'Perfumería', icon: '🧴', defaultOrder: 10 },
    { id: 'sec_pets', name: 'Mascotas', icon: '🐶', defaultOrder: 11 },
    { id: 'sec_other', name: 'Otros', icon: '📦', defaultOrder: 99 },
];

export const INITIAL_STORE: StoreProfile = {
    id: 'store_default',
    name: 'Mi Mercadona',
    sections: DEFAULT_SECTIONS.sort((a, b) => a.defaultOrder - b.defaultOrder).map(s => s.id),
};

// Enhanced mapping for auto-categorization
// Note: The algorithm searches for these keywords in the product name (case insensitive)
// First match wins, so order matters for disambiguation
export const PRODUCT_CATEGORY_MAP: Record<string, string> = {
    // Limpieza y Hogar (Subido para evitar conflictos con 'te' en detergente)
    'detergente': 'sec_cleaning',
    'suavizante': 'sec_cleaning',
    'lejia': 'sec_cleaning',
    'fregasuelos': 'sec_cleaning',
    'lavavajillas': 'sec_cleaning',
    'limpiador': 'sec_cleaning',
    'papel cocina': 'sec_cleaning',
    'papel higienico': 'sec_cleaning',
    'servilleta': 'sec_cleaning',
    'pañuelo': 'sec_cleaning',
    'bolsa basura': 'sec_cleaning',
    'estropajo': 'sec_cleaning',
    'bayeta': 'sec_cleaning',
    'fregona': 'sec_cleaning',

    // Fruta y Verdura
    'tomate': 'sec_fruit',
    'cherry': 'sec_fruit',
    'cherries': 'sec_fruit',
    'lechuga': 'sec_fruit',
    'cebolla': 'sec_fruit',
    'patata': 'sec_fruit',
    'zanahoria': 'sec_fruit',
    'pimiento': 'sec_fruit',
    'calabacin': 'sec_fruit',
    'calabaza': 'sec_fruit',
    'pepino': 'sec_fruit',
    'brocoli': 'sec_fruit',
    'coliflor': 'sec_fruit',
    'esparrago': 'sec_fruit',
    'berenjena': 'sec_fruit',
    'melon': 'sec_fruit',
    'sandia': 'sec_fruit',
    'platano': 'sec_fruit',
    'manzana': 'sec_fruit',
    'pera': 'sec_fruit',
    'naranja': 'sec_fruit',
    'mandarina': 'sec_fruit',
    'limon': 'sec_fruit',
    'kiwi': 'sec_fruit',
    'fresa': 'sec_fruit',
    'uva': 'sec_fruit',
    'aguacate': 'sec_fruit',
    'ajo': 'sec_fruit',
    'perejil': 'sec_fruit',
    'cilantro': 'sec_fruit',
    'espinaca': 'sec_fruit',
    'rucula': 'sec_fruit',
    'acelga': 'sec_fruit',

    // Panadería
    'pan': 'sec_bakery',
    'barra': 'sec_bakery',
    'baguette': 'sec_bakery',
    'chapata': 'sec_bakery',
    'molde': 'sec_bakery',
    'croissant': 'sec_bakery',
    'napolitana': 'sec_bakery',
    'palmera': 'sec_bakery',
    'ensaimada': 'sec_bakery',
    'magdalena': 'sec_bakery',
    'bizcocho': 'sec_bakery',

    // Charcutería y Quesos
    'jamon': 'sec_deli',
    'serrano': 'sec_deli',
    'york': 'sec_deli',
    'pavo': 'sec_deli',
    'lomo': 'sec_deli',
    'salchichon': 'sec_deli',
    'chorizo': 'sec_deli',
    'fuet': 'sec_deli',
    'queso': 'sec_deli',
    'manchego': 'sec_deli',
    'curado': 'sec_deli',
    'semicurado': 'sec_deli',
    'mozzarella': 'sec_deli',
    'parmesano': 'sec_deli',
    'emmental': 'sec_deli',
    'cheddar': 'sec_deli',

    // Carnicería
    'filete': 'sec_meat',
    'filetes': 'sec_meat',
    'solomillo': 'sec_meat',
    'entrecot': 'sec_meat',
    'ternera': 'sec_meat',
    'cerdo': 'sec_meat',
    'cordero': 'sec_meat',
    'costilla': 'sec_meat',
    'chuleta': 'sec_meat',
    'picada': 'sec_meat',
    'carne': 'sec_meat',
    'hamburgues': 'sec_meat',
    'pollo': 'sec_meat',
    'pechuga': 'sec_meat',
    'muslo': 'sec_meat',
    'alas': 'sec_meat',

    // Pescadería
    'pescado': 'sec_fish',
    'merluza': 'sec_fish',
    'salmon': 'sec_fish',
    'dorada': 'sec_fish',
    'lubina': 'sec_fish',
    'bacalao': 'sec_fish',
    'rape': 'sec_fish',
    'atun fresco': 'sec_fish',
    'calamar': 'sec_fish',
    'pulpo': 'sec_fish',
    'sepia': 'sec_fish',
    'gamba': 'sec_fish',
    'langostino': 'sec_fish',
    'mejillon': 'sec_fish',
    'almeja': 'sec_fish',

    // Refrigerados
    'leche': 'sec_fridge',
    'yogur': 'sec_fridge',
    'yogurt': 'sec_fridge',
    'natillas': 'sec_fridge',
    'flan': 'sec_fridge',
    'nata': 'sec_fridge',
    'mantequilla': 'sec_fridge',
    'margarina': 'sec_fridge',
    'huevo': 'sec_fridge',
    'pizza': 'sec_fridge',
    'lasaña': 'sec_fridge',
    'canelones': 'sec_fridge',
    'tortellini': 'sec_fridge',
    'ravioli': 'sec_fridge',
    'zumo refrigerado': 'sec_fridge',
    'batido': 'sec_fridge',

    // Despensa
    'arroz': 'sec_pantry',
    'pasta': 'sec_pantry',
    'espagueti': 'sec_pantry',
    'macarrones': 'sec_pantry',
    'fideos': 'sec_pantry',
    'sopa': 'sec_pantry',
    'caldo': 'sec_pantry',
    'tomate frito': 'sec_pantry',
    'atun': 'sec_pantry',
    'bonito': 'sec_pantry',
    'sardinilla': 'sec_pantry',
    'mejillon en conserva': 'sec_pantry',
    'lata': 'sec_pantry',
    'conserva': 'sec_pantry',
    'aceite': 'sec_pantry',
    'vinagre': 'sec_pantry',
    'sal': 'sec_pantry',
    'azucar': 'sec_pantry',
    'harina': 'sec_pantry',
    'legumbre': 'sec_pantry',
    'garbanzo': 'sec_pantry',
    'lenteja': 'sec_pantry',
    'alubia': 'sec_pantry',
    'galleta': 'sec_pantry',
    'cereales': 'sec_pantry',
    'chocolate': 'sec_pantry',
    'cafe': 'sec_pantry',
    'te': 'sec_pantry',
    'infusion': 'sec_pantry',

    // Congelados
    'congelado': 'sec_frozen',
    'helado': 'sec_frozen',
    'hielo': 'sec_frozen',
    'guisante': 'sec_frozen',
    'judia': 'sec_frozen',
    'alcachofa': 'sec_frozen',
    'croqueta': 'sec_frozen',
    'empanadilla': 'sec_frozen',
    'nugget': 'sec_frozen',
    'varita': 'sec_frozen',

    // Bebidas
    'coca': 'sec_drinks',
    'cola': 'sec_drinks',
    'pepsi': 'sec_drinks',
    'fanta': 'sec_drinks',
    'sprite': 'sec_drinks',
    'nestea': 'sec_drinks',
    'aquarius': 'sec_drinks',
    'refresco': 'sec_drinks',
    'zumo': 'sec_drinks',
    'agua': 'sec_drinks',
    'cerveza': 'sec_drinks',
    'vino': 'sec_drinks',
    'cava': 'sec_drinks',
    'sangria': 'sec_drinks',
    'tonica': 'sec_drinks',

    // Perfumería
    'champu': 'sec_personal',
    'shampoo': 'sec_personal',
    'gel': 'sec_personal',
    'jabon': 'sec_personal',
    'crema': 'sec_personal',
    'desodorante': 'sec_personal',
    'colonia': 'sec_personal',
    'perfume': 'sec_personal',
    'dentifrico': 'sec_personal',
    'pasta dientes': 'sec_personal',
    'cepillo': 'sec_personal',
    'maquinilla': 'sec_personal',
    'espuma afeitar': 'sec_personal',
    'pañal': 'sec_personal',
    'toallita': 'sec_personal',
    'compresa': 'sec_personal',
    'tampon': 'sec_personal',

    // Mascotas
    'pienso': 'sec_pets',
    'comida perro': 'sec_pets',
    'comida gato': 'sec_pets',
    'arena gato': 'sec_pets',
    'lata perro': 'sec_pets',
    'lata gato': 'sec_pets',
};
